# Generated by Django 4.2.5 on 2023-10-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='vanue',
            name='vanue_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
