# Generated by Django 4.2.5 on 2023-10-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_vanue_vanue_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vanue',
            name='owner',
            field=models.IntegerField(default=1, verbose_name='Venue Owner'),
        ),
    ]
